version: '3.4'
services:
  app-1:
    container_name: app_1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/
    ports:
      - 80:80
    env_file:
      - .env
    networks:
      - bubble
networks:
  bubble:
    external: true