version: '3.4'
services:
  xml2json:
    container_name: xml2json
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - bubble
networks:
  bubble:
    external: true